version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  frontend:
    build:
      context: ./frontend
    ports:
      - "2000:2000"
    environment:
      BASE_URL: http://localhost:3000
